### ISSUE TITLE
Add the possibility to print log in files

### ISSUE THREAD

**Issue by alessandroargentieri** [gyozatech/noodlog#10]
**User Story**

As a developer, I would like to have the possibility to choose to redirect all logs in a file (one file for the day) in place of standard output.

**Detailed Description**
Add a setting to define filename, log rotation, etc. and switch the logic when needed.

**Comment by ilmanzo** [comment]
as a suggestion: create a `NewLogger() `constructor that takes as input an `io.Writer` interface ( https://golang.org/pkg/io/#Writer ) plus a struct with other settings, and returns a logger object; so the user can choose to log in a file, stderr or even a memory buffer , for testing/benchmark purposes.

**Comment by alessandroargentieri** [comment]
> as a suggestion: create a `NewLogger() `constructor that takes as input an `io.Writer` interface ( https://golang.org/pkg/io/#Writer ) plus a struct with other settings, and returns a logger object; so the user can choose to log in a file, stderr or even a memory buffer , for testing/benchmark purposes.

many thanks!
