### ISSUE TITLE
Test TestSimpleLogger is flaky

### ISSUE THREAD

**Issue by davideimola** [gyozatech/noodlog#21]
**Bug description**

The test `TestSimpleLogger` is a bit flaky. We must resolve the flakiness.

**How to reproduce**

Run the tests without cache and you can see the test can go both green and red.

**Comment by ilmanzo** [comment]
Being a "global" logger, the output of each test depends on the order of execution. Keep in mind that GO tests are run in parallel. If a test executes before and that test sets the loglevel to another, then the Info() func outputs nothing. This is IMHO the main architectural issue that must be solved. 

As a temporary workaround, I recommend to run tests with

`go test -p=1` 

and I'll send a PR to set the loglevel to a known value before running this specific test.
