### ISSUE TITLE
Logs don't go new line

### ISSUE THREAD

**Issue by alessandroargentieri** [gyozatech/noodlog#27]
**Bug description**

The log messages don't go to next line.

**How to reproduce**

Just check the logged messages

**Environment**

- Go version 16+
- OS and Architecture: any

**Anything else**

**Hint**: change the `fmt.Fprintf()` function into `fmt.Fprintln()`  into logger.go -> printLog function.

**Comment by amoghrajesh** [comment]
@alessandroargentieri I would like to give this issue a shot. Is it considered for Hacktoberfest 2021? If yes, let me know how I can onboard myself with this and start contributing.

**Comment by alessandroargentieri** [comment]
Hi, I don't know which are the requisites for that initiative. This project is open source, so if the requisite is to contribute to any open source project Pi think it's OK. Can you get informed and let me know? If you are interested I can give you some more good first issues

**Comment by amoghrajesh** [comment]
@alessandroargentieri you have to add a hacktoberfest label to your issues and maintain the project with respect to the guidelines in [here](https://hacktoberfest.digitalocean.com/resources/maintainers) and it will be counted. I am interested in this issue. I need to know how to start.

**Comment by alessandroargentieri** [comment]
Nice job, thanks! It's a very nice initiative. I'll apply the label on monday. So wait until it's applied. Anyway the solution is guided in the bug description. If you have any problems, feel free to contact me

**Comment by amoghrajesh** [comment]
@alessandroargentieri please assign this issue to me. I will attempt to solve it and create a PR for it.

**Comment by amoghrajesh** [comment]
@alessandroargentieri I have created a patch that attempts to fix this issue. Please let me know how it can be tested locally and feel free to review it. Thanks! https://github.com/gyozatech/noodlog/pull/28
